# Generated by Django 3.2 on 2021-05-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flopfarm_admin', '0003_alter_instance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='API_price',
            field=models.FloatField(blank=True, help_text='Enter the price per use for API', null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='APIinfo',
            field=models.CharField(blank=True, help_text='Enter the API info', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='CPU',
            field=models.CharField(blank=True, help_text='Enter the CPU info', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='GPU',
            field=models.CharField(blank=True, help_text='Enter the GPU info', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='OS',
            field=models.CharField(blank=True, help_text='Enter the Operating System info', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='RAM',
            field=models.CharField(blank=True, help_text='Enter the RAM info', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='hourly_price',
            field=models.FloatField(blank=True, help_text='Enter the hourly price', null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='remarks',
            field=models.CharField(blank=True, help_text='Enter the remarks', max_length=200, null=True),
        ),
    ]
