# Generated by Django 3.2 on 2021-05-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flopfarm_admin', '0006_auto_20210502_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='e_time',
            field=models.DateTimeField(blank=True, help_text='end running time', null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='s_time',
            field=models.DateTimeField(blank=True, help_text='Start running time', null=True),
        ),
    ]
